import type { Metadata } from "next";
import { ClerkProvider } from "@clerk/nextjs";

import "./globals.css";
import { ApolloProvider } from "@/providers/ApolloProvider";
import { Toaster } from "sonner";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <ApolloProvider>
      <ClerkProvider>
        <html lang="en">
          <body className={`antialiased min-h-screen flex`}>
            {children}

            <Toaster richColors position="top-center" />
          </body>
        </html>
      </ClerkProvider>
    </ApolloProvider>
  );
}
